apiVersion: app.example.com/v1alpha1
kind: GontadorService
metadata:
  name: example-gontadorservice
spec:
  # Add fields here
  containers:
    - name: busybox
      image: busybox:1.25
      command:
        - /bin/sh
        - -ec
        - |
          if [ -f /persistent/log ]; then
            echo -n "Found old state starting at "; head -n1 /persistent/log
          else
            echo -n "Starting with a fresh state"
          fi
          while sleep 5; do date | tee -a /persistent/log; done
