apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gontadorservices.app.example.com
spec:
  group: app.example.com
  names:
    kind: GontadorService
    listKind: GontadorServiceList
    plural: gontadorservices
    singular: gontadorservice
  scope: Namespaced
  version: v1alpha1
  subresources:
    status: {}
