apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: operator
  template:
    metadata:
      labels:
        name: operator
    spec:
      serviceAccountName: operator
      containers:
        - name: operator
          # Replace this with the built image name
          image: 172.30.1.1:5000/gontador/goperador:latest
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - operator
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "operator"
